# Flights
YEAR = "YEAR"
MONTH = "MONTH"
DAY = "DAY"
DAY_OF_WEEK = "DAY_OF_WEEK"
AIRLINE = "AIRLINE"
FLIGHT_NUMBER = "FLIGHT_NUMBER"
TAIL_NUMBER = "TAIL_NUMBER"
ORIGIN_AIRPORT = "ORIGIN_AIRPORT"
DESTINATION_AIRPORT = "DESTINATION_AIRPORT"
SCHEDULED_DEPARTURE = "SCHEDULED_DEPARTURE"
DEPARTURE_TIME = "DEPARTURE_TIME"
DEPARTURE_DELAY = "DEPARTURE_DELAY"
TAXI_OUT = "TAXI_OUT"
WHEELS_OFF = "WHEELS_OFF"
SCHEDULED_TIME = "SCHEDULED_TIME"
ELAPSED_TIME = "ELAPSED_TIME"
AIR_TIME = "AIR_TIME"
DISTANCE = "DISTANCE"
WHEELS_ON = "WHEELS_ON"
TAXI_IN = "TAXI_IN"
SCHEDULED_ARRIVAL = "SCHEDULED_ARRIVAL"
ARRIVAL_TIME = "ARRIVAL_TIME"
ARRIVAL_DELAY = "ARRIVAL_DELAY"
DIVERTED = "DIVERTED"
CANCELLED = "CANCELLED"
CANCELLATION_REASON = "CANCELLATION_REASON"
AIR_SYSTEM_DELAY = "AIR_SYSTEM_DELAY"
SECURITY_DELAY = "SECURITY_DELAY"
AIRLINE_DELAY = "AIRLINE_DELAY"
LATE_AIRCRAFT_DELAY = "LATE_AIRCRAFT_DELAY"
WEATHER_DELAY = "WEATHER_DELAY"

FLIGHTS_COLUMN_NAMES = (
    "YEAR", "MONTH", "DAY", "DAY_OF_WEEK", "AIRLINE", "FLIGHT_NUMBER",
    "TAIL_NUMBER", "ORIGIN_AIRPORT", "DESTINATION_AIRPORT", "SCHEDULED_DEPARTURE",
    "DEPARTURE_TIME", "DEPARTURE_DELAY", "TAXI_OUT", "WHEELS_OFF", "SCHEDULED_TIME",
    "ELAPSED_TIME", "AIR_TIME", "DISTANCE", "WHEELS_ON", "TAXI_IN", "SCHEDULED_ARRIVAL",
    "ARRIVAL_TIME", "ARRIVAL_DELAY", "DIVERTED", "CANCELLED", "CANCELLATION_REASON",
    "AIR_SYSTEM_DELAY", "SECURITY_DELAY", "AIRLINE_DELAY", "LATE_AIRCRAFT_DELAY",
    "WEATHER_DELAY"
)

# Cancellation Codes
CANCELLATION_DESCRIPTION = "CANCELLATION_DESCRIPTION"

CC_COLUMN_NAMES = (CANCELLATION_REASON, CANCELLATION_DESCRIPTION)

# Airlines
IATA_CODE = "IATA_CODE"
AIRLINE_NAME = "AIRLINE_NAME"

AIRLINES_COLUMN_NAMES = (IATA_CODE, AIRLINE)

# Airports
AIRPORT_NAME = "AIRPORT_NAME"
AIRPORT_COLUMN_NAMES = (IATA_CODE,"AIRPORT", "CITY", "STATE", "COUNTRY", "LATITUDE", "LONGITUDE")
